### ISSUE TITLE
Peer review - Daniel Sarabi

### ISSUE THREAD

**Issue by danielsarabi** [teokem/project-work-2020-elskorda#2]
In your README on GitHub you have given the wrong adress to your git clone, I copied the adress given by github and it did work but not with the link that you have given in the instructions. Also the environment.yml was not able to be created using 
`conda env create -f environment.yml` 
which was in your git repository. 
Also the link to the environment.yml in your README points to LU compute environment which is a bit confusing. Some paragraphs have wrong spelling which is a easy fix. It would also be nice if you had some comments on the code as well to better understand what the code does and how it relates to the expression/algorithms shown in the markdown blocks. Interesting work though and fun to read through. Thanks! 

- [x] **Documentation:**

- [x] title and abstract of the project (max 300 words)

- [x]  includes instructions on how to run the notebook

- [x] includes the required packages in an environment.yml file - _I think this part can be improved, as I wasn't able to create the environment based on the .yml file given in the repository_

- [x]  includes a brief explanation of the reason each package/library was used - _A short description when you import packages would be good._

- [x]  includes rich documentation using Markdown (equations, tables, links, images or videos)

- [x]  is reproducible, i.e., someone else should be able to redo the steps

- [x] **Input/Output:**

- [ ] uses pandas to read large data sets or numpy to load data from text files
 
- [x] uses pandas to save to disk the processed or generated data - _Im not sure if the data was saved to disk. Maybe you can save the variable asymm225 as data frame using pandas._ 

- [x] **Scientific computing/data processing:**
 
- [x] performs numerical operations (numpy, scipy, pandas) or manipulates, groups, and aggregates a data set (pandas)

- [x] **Data visualization:**

- [x]  includes at least one composite plot (inset or multiple panels)

- [x]  produces publication ready quality figures 

- [x] the figures are 89 mm wide (single column) or 183 mm wide (double column) - _there are no specifications given to the figures such as size or resolution._

- [x] the axes are labeled

- [x] the font sizes are sufficiently large

- [x] the figures are saved as publish ready images (300 dpi) or vector art - _I could not see that the figures were saved nor saved as 300 dpi. Use of more figure optionwould be recommended._ 

- [x]  **Version control, sharing, and archiving:**

- [x]  is archived in a repository with a digital object identifier (DOI) - _I don't know if this work has a DOI, if so I could not see it in the documentation._

**Comment by elskorda** [comment]
Dear Daniel, 

Thank you for providing such a detailed feedback with this very useful checklist :) Here are some answers to your comments:
> 
> 
> In your README on GitHub you have given the wrong adress to your git clone, I copied the adress given by github and it did work but not with the link that you have given in the instructions. Also the environment.yml was not able to be created using
> `conda env create -f environment.yml`
> which was in your git repository.

I re-run all the instructions from 0 and I was able to create a new environment and checkout the git repository. .  Did you create or have an ssh key ? Also I created the environment again. I am not sure how to address this

> Also the link to the environment.yml in your README points to LU compute environment which is a bit confusing. 
If one wants to install some extras using my environment will not be able to do since it has only the libraries to run the particular notebook. For example pip is missing from my environment since one doesn't need it to run the particular notebook. I hope in the new Readme this is more clear now.  

For the rest of your comments I ticked the really nice check list you provided and they are implemented in the updated version of the notebook 

Best,
Eleni
